## WhatsApp

In [1]:
import pandas as pd 

# Lendo o CSV
df = pd.read_csv("../Datasets/Correto_whatsapp_rotulado_revisado.csv")

In [3]:
df.head()

                              text_content_anonymous  preconceito
0  Show :clapping_hands_light_skin_tone::clapping...            0
1  Mais uma vez o PT= Partido das Trevas apela ao...            1
2  Se não puder avise só para não quebrar a vigíl...            0
3              E a esquerda tenta impedir o trabalho            0
4  Deus perdoa porque eles Não sabem que fazem e ...            0

In [4]:
df.shape

(3000, 2)

In [2]:
df['id'] = range(len(df))
df.head()

                              text_content_anonymous  preconceito  id
0  Show :clapping_hands_light_skin_tone::clapping...            0   0
1  Mais uma vez o PT= Partido das Trevas apela ao...            1   1
2  Se não puder avise só para não quebrar a vigíl...            0   2
3              E a esquerda tenta impedir o trabalho            0   3
4  Deus perdoa porque eles Não sabem que fazem e ...            0   4

In [3]:
print(df.isnull().sum())

text_content_anonymous    0
preconceito               0
id                        0
dtype: int64

In [4]:
df.shape

(3000, 3)

In [5]:
# === Amostragem balanceada ===
df_0 = df[df["preconceito"] == 0].sample(n=300, random_state=42)
df_1 = df[df["preconceito"] == 1].sample(n=300, random_state=42)

# Combina e embaralha
df_sample = pd.concat([df_0, df_1]).sample(frac=1, random_state=42).reset_index(drop=True)

# === Garante que o restante NÃO tenha os mesmos textos ===
df_restante = df[~df["text_content_anonymous"].isin(df_sample["text_content_anonymous"])]

# === Salva ===
df_sample.to_csv("./datasets/wpp/amostra_balanceada_com_rotulo.csv", index=False)
df_restante.to_csv("./datasets/wpp/dados_restantes.csv", index=False)

print("Amostra balanceada:", df_sample.shape)
print("Restante:", df_restante.shape)

Amostra balanceada: (600, 3)
Restante: (2400, 3)

In [6]:
duplicadas = set(df_sample["text_content_anonymous"]) & set(df_restante["text_content_anonymous"])
print("Mensagens duplicadas:", len(duplicadas))

Mensagens duplicadas: 0

In [7]:
df_sample[["text_content_anonymous", "id"]].to_csv(
    "./datasets/wpp/amostra_balanceada_sem_rotulo.csv",
    index=False
)

In [8]:
df_restante[["text_content_anonymous", "id"]].to_csv(
    "./datasets/wpp/df_restantes_sem_rotulos.csv",
    index=False
)

## Telegram

In [9]:
import pandas as pd 

# Lendo o CSV
df = pd.read_csv("../Datasets/Telegram_Tratado_Rotulado_Revisado_Final.csv")
df.head()

                              text_content_anonymous  preconceito
0  Sim, eu sou um "decepcionado"!\n\nEu vejo pess...            0
1  Em épocas com muitos eventos grandes, altas qu...            0
2  Algumas premissas que ele adotou:\n- Ser de di...            0
3  Apocalipse 22:11. Cristo fez expiação por Seu ...            0
4  :sun_with_face:S:rose:H:cherry_blossom:A:sunfl...            0

In [3]:
df.shape

(3000, 2)

In [14]:
df['id'] = range(len(df))
df.head()

                              text_content_anonymous  preconceito  id
0  Sim, eu sou um "decepcionado"!\n\nEu vejo pess...            0   0
1  Em épocas com muitos eventos grandes, altas qu...            0   1
2  Algumas premissas que ele adotou:\n- Ser de di...            0   2
3  Apocalipse 22:11. Cristo fez expiação por Seu ...            0   3
4  :sun_with_face:S:rose:H:cherry_blossom:A:sunfl...            0   4

In [5]:
print(df.isnull().sum())

text_content_anonymous    0
preconceito               0
id                        0
dtype: int64

In [15]:
# === Amostragem balanceada ===
df_0 = df[df["preconceito"] == 0].sample(n=300, random_state=42)
df_1 = df[df["preconceito"] == 1].sample(n=300, random_state=42)

# Combina e embaralha
df_sample = pd.concat([df_0, df_1]).sample(frac=1, random_state=42).reset_index(drop=True)

# === Garante que o restante NÃO tenha os mesmos textos ===
df_restante = df[~df["text_content_anonymous"].isin(df_sample["text_content_anonymous"])]

# === Salva ===
df_sample.to_csv("./datasets/telegram/amostra_balanceada_com_rotulo.csv", index=False)
df_restante.to_csv("./datasets/telegram/dados_restantes.csv", index=False)

print("Amostra balanceada:", df_sample.shape)
print("Restante:", df_restante.shape)

Amostra balanceada: (600, 3)
Restante: (2399, 3)

In [16]:
df_sample

                                text_content_anonymous  preconceito    id
0    Todos que são do Bolsonaro sai imediatamente d...            0   481
1    Eu confesso, não tenho paciência com os parent...            1  2588
2    Isentão você desceu do muro, agora está do lad...            1  2663
3    Acho q o canal no telegram q foi bloqueado,pq ...            0   522
4    Meu Deus a mídia sempre foi nossa inimiga, um ...            0   582
..                                                 ...          ...   ...
595  As abstenções chegaram a um número absurdo de ...            0   852
596  Pessoal não acreditem nestas postagens da esqu...            0    59
597  Gostaria que tivessem feito isso no nordeste p...            0   353
598  Bolsonaro foi na loja em campanha eleitoral. I...            1  1515
599  :Brazil: ATENÇÃO, PATRIOTAS! :Brazil:\n\nNÃO É...            0  1134

[600 rows x 3 columns]

In [17]:
duplicadas = set(df_sample["text_content_anonymous"]) & set(df_restante["text_content_anonymous"])
print("Mensagens duplicadas:", len(duplicadas))

Mensagens duplicadas: 0

In [18]:
df_sample[["text_content_anonymous", "id"]].to_csv(
    "./datasets/telegram/amostra_balanceada_sem_rotulo.csv",
    index=False
)

In [20]:
df_restante[["text_content_anonymous", "id"]].to_csv(
    "./datasets/telegram/df_restantes_sem_rotulos.csv",
    index=False
)